name: Auto-merge Dependabot PRs
on: pull_request_target
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4.0.0

      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          # Auto merge even major changes as long as the tests all pass
          target: major
          github-token: ${{secrets.AUTO_MERGE_TOKEN}}
          command: squash and merge
